services:
  dns:
    build: ./dns
    container_name: dns-server
    networks:
      servidores:
        ipv4_address: 172.20.1.10
    privileged: true
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
    restart: unless-stopped

  dhcp:
    build: ./dhcp
    container_name: dhcp-server
    networks:
      servidores:
        ipv4_address: 172.20.1.12
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      - dhcp_data:/var/lib/dhcp
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  ftp:
    build: ./ftp
    container_name: ftp-server
    networks:
      servidores:
        ipv4_address: 172.20.1.16
    volumes:
      - ftp_data:/home/vsftpd_users:rw
      - ./ftp/vsftpd.conf:/etc/vsftpd.conf:ro
    ports:
      - "2121:21"                    # Porta FTP (controle)
      - "20000-21000:20000-21000"    # Faixa de portas para modo passivo
    entrypoint: ["/entrypoint.sh"]
    restart: unless-stopped

  ldap:
    image: bitnami/openldap:latest
    container_name: ldap-server
    networks:
      servidores:
        ipv4_address: 172.20.1.18
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_ROOT: dc=intranet,dc=local
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin123
      LDAP_CUSTOM_LDIF_DIR: /ldifs
      LDAP_SKIP_DEFAULT_TREE: yes
      LDAP_LISTEN: "0.0.0.0"
      LDAP_EXTRA_FLAGS: "-h ldap://0.0.0.0"
    volumes:
      - ldap_data:/bitnami/openldap
      - ./ldap/ldifs:/ldifs

    restart: unless-stopped

  samba:
    build: ./samba
    container_name: samba-server
    networks:
      servidores:
        ipv4_address: 172.20.1.20
    volumes:
      - ./samba/smb.conf:/etc/samba/conf.d/smb.conf:ro
      - samba_share_data:/srv/samba_share
    restart: unless-stopped

  router:
    build: ./router
    container_name: router
    networks:
      servidores:
        ipv4_address: 172.20.1.7
      clientes:
        ipv4_address: 172.20.2.7
    privileged: true
    restart: unless-stopped

  web:
    build: ./web
    container_name: web-server
    networks:
      servidores:
        ipv4_address: 172.20.1.14
    volumes:
      - ./web/index.html:/var/www/html/index.html:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  cliente:
    build: ./cliente
    container_name: cliente1
    networks:
      clientes: {}
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    restart: unless-stopped

networks:
  servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1

  clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1

volumes:
  dhcp_data:
  ldap_data:
  samba_share_data:
  ftp_data:
