
services:
  dns:
    build: ./dns
    container_name: dns-server
    networks:
      servidores:
        ipv4_address: 172.20.1.10
    cap_add:
      - NET_ADMIN
    ports:
      - "10053:53/tcp"
      - "10053:53/udp"
    restart: unless-stopped

  dhcp:
    build: ./dhcp
    container_name: dhcp-server
    networks:
      servidores:
        ipv4_address: 172.20.1.12
    volumes:
      - ./dhcp/dhcpd.conf:/etc/dhcp/dhcpd.conf:ro
      - dhcp_data:/var/lib/dhcp
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  ftp:
    build: stilliard/pure-ftpd
    container_name: ftp-server
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ./ftp:/home/ftpusers
    networks:
      servidores:
        ipv4_address: 172.20.1.16
    restart: unless-stopped

  ldap:
    build: osixia/openldap:1.5.0
    container_name: ldap-server
    networks:
      servidores:
        ipv4_address: 172.20.1.18
    volumes:
      - .ldap/data:/var/lib/ldap
      - .ldap/config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=intranet
      - LDAP_DOMAIN=intranet.local
      - LDAP_ADMIN_PASSWORD=admin
    restart: unless-stopped

  samba:
    build: ./samba
    container_name: samba-server
    networks:
      servidores:
        ipv4_address: 172.20.1.20
    volumes:
      - samba_share_data:/samba/public
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  router:
    build: ./router
    container_name: router
    privileged: true
    networks:
      servidores:
        ipv4_address: 172.20.1.7
      clientes:
        ipv4_address: 172.20.2.7
    restart: unless-stopped

  web:
    build: ./web
    container_name: web-server
    networks:
      servidores:
        ipv4_address: 172.20.1.14
    volumes:
      - ./web/index.html:/var/www/html/index.html:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  cliente:
    build: ./cliente
    container_name: cliente1
    networks:
      clientes:
        ipv4_address: 172.20.2.10
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    restart: unless-stopped

networks:
  servidores:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
          gateway: 172.20.1.1

  clientes:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.2.0/24
          gateway: 172.20.2.1

volumes:
  dhcp_data:
  ldap_data:
  ldap_config:
  samba_share_data:
